FROM node:20-alpine

RUN apk add --no-cache openssl libc6-compat

WORKDIR /app

COPY package.json package-lock.json* ./
COPY prisma ./prisma/

RUN npm ci

RUN npx prisma generate

COPY . .

EXPOSE 3000 9229

CMD ["npx", "ts-node-dev", "--respawn", "--transpile-only", "--inspect=0.0.0.0:9229", "src/index.ts"]
